name: Compile Sketch

# The workflow will run on every push to the repository
on:
  - push

jobs:
  compile-sketch:
    runs-on: ubuntu-latest

    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v2

      # For more information: https://github.com/arduino/compile-sketches#readme
      - name: Set project
        working-directory: ./ArduinoProject
      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          # The default is to compile for the Arduino Uno board. If you want to compile for other boards, use the `fqbn` input.
          sketch-paths: |
            # Configure the action to search all folders under the root of the repository for sketches and compile them.
            # This is formatted as a YAML list, which makes it possible to have multiple sketch paths if needed.
            - ./
          libraries: |
            - name: "DHT_nonblocking"
              source-url: https://github.com/olewolf/DHT_nonblocking.git
            - name: "PubSubClient"
              source-url: https://github.com/knolleary/pubsubclient.git
